CREATE TABLE bookstore.books(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  title VARCHAR(100),
  price INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kadaidb.person(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(50),
  age INT, 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);